// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Support both local SQLite and remote Turso
const tursoUrl = process.env["TURSO_DATABASE_URL"];
const databaseUrl = tursoUrl || process.env["DATABASE_URL"] || "file:./dev.db";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
